export const queryKeys = {
  userUnits: ['userUnits'] as const,
  userCategories: ['userCategories'] as const,
  ingredients: ['ingredients'] as const,
  ingredient: (id: string) => ['ingredients', id] as const,
  storageLocations: ['storageLocations'] as const,
  inventory: (locationId?: string | null) => ['inventory', locationId ?? 'all'] as const,
  inventoryItem: (id: string) => ['inventory', 'item', id] as const,
  shoppingLists: (status?: 'active' | 'archived') => ['shoppingLists', status ?? 'all'] as const,
  shoppingList: (listId: string) => ['shoppingList', listId] as const,
  mealPlan: (start: string, end: string) => ['mealPlan', start, end] as const,
  recipes: (filters?: Record<string, unknown>) => ['recipes', filters ?? {}] as const,
  recipe: (id: string) => ['recipes', id] as const,
  notes: ['notes'] as const,
};
